name: Check

on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

        # Use itself to setup pnpm with caching
      - name: Run `@oBusk/action-pnpm-setup` (this repo)
        uses: ./

      - name: Print versions
        shell: bash
        run: |
          echo -e "\033[34mnode -v\033[0m"
          node -v
          echo -e "\033[34mpnpm -v\033[0m"
          pnpm -v
          pnpm run versions

      - name: Run prettier
        run: pnpm run prettier
